# Permalinks
# Setup
title:               Casual Snippets
tagline:             'insights on software development'
url:                 http://nmat.me
baseurl:             ''
paginate:            5
permalink:           blog/:year/:month/:day/:title/

# About/contact
author:
  name:              Nuno Teixeira
  url:               https://twitter.com/mdo
  email:             nuno.miguel.t@gmail.com

# Custom vars
link-so:             http://stackoverflow.com/u/848330
link-ln:             https://linkedin.com/in/nmatpt
link-gh:             http://github.com/nmatpt
link-tw:             http://twitter.com/nmat
link-uw:             http://www.upwork.com/o/profiles/users/_~01ddcce074b962b194/
email-address:       nuno.miguel.t@gmail.com

# Gems
gems: [jekyll-paginate]
