# Permalinks
# Setup
title:               Some title
tagline:             'Some tagline'
description:         'Some description'
url:                 http://nmat.me
baseurl:             ''
paginate:            5
permalink:           blog/:year/:month/:day/:title/

# About/contact
author:
  name:              Nuno Teixeira
  url:               https://twitter.com/mdo
  email:             nuno.miguel.t@gmail.com

# Custom vars
version:             1.0.0

# Gems
gems: [jekyll-paginate]
